spring:
    datasource:
         driverClassName: com.mysql.jdbc.Driver
         url: jdbc:mysql://localhost:3306/jobportal_local
         username: root
         password: 
    jpa:
        hibernate.ddl-auto: create-drop
        generate-ddl: true
        show-sql: true
    session:
        store-type: jdbc